//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apnea
    {
        public int Id_Apnea { get; set; }
        public string Tipo_licencia { get; set; }
        public bool Trabaja_de_noche { get; set; }
        public Nullable<int> Dias_trabajo { get; set; }
        public Nullable<int> Dias_descanso { get; set; }
        public bool Apnea_del_sueno { get; set; }
        public Nullable<System.DateTime> Ultimo_control { get; set; }
        public bool HTA { get; set; }
        public string Medicacion { get; set; }
        public bool Polisomnografía_PSG { get; set; }
        public Nullable<System.DateTime> Fecha_ultima_PSG { get; set; }
        public bool En_mina { get; set; }
        public bool Fuera_de_mina { get; set; }
        public bool Se_cabeceo { get; set; }
        public bool Accidente_en_ultimas_5_horas { get; set; }
        public bool Ausencia_de_evidencia_de_maniobra { get; set; }
        public bool Colision_frontal_del_vehiculo { get; set; }
        public bool Vehiculo_que_invadio { get; set; }
        public bool El_conductor_no_recuerda { get; set; }
        public bool El_conductor_tomo_una_medicacion { get; set; }
        public bool El_conductor_se_encontraba_en_horas_extras { get; set; }
        public bool Accidente_por_somnolencia { get; set; }
        public bool Accidente_con_alta_sospecha { get; set; }
        public bool Accidente_con_escasa_evidencia { get; set; }
        public bool No_se_dispone_de_datos_suficientes { get; set; }
        public bool Accidente_no_debido_a_somnolencia { get; set; }
        public bool Su_esposa_comento_que_ronca { get; set; }
        public bool Su_esposa_comento_que_hace_ruidos { get; set; }
        public bool Su_esposa_comento_que_deja_de_respirar { get; set; }
        public bool Siente_mas_que_tiene_mas_sueno { get; set; }
        public bool Tiene_familiar_con_apnea { get; set; }
        public bool Accidente_por_falla_humana { get; set; }
        public bool Recibe_tratamiento_para_apnea { get; set; }
        public bool Se_le_ha_relizado_una_PSG { get; set; }
        public Nullable<int> Puntuacion_epwhorth { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Talla { get; set; }
        public Nullable<decimal> IMC { get; set; }
        public bool Varon_normal { get; set; }
        public bool Mujer_normal { get; set; }
        public Nullable<decimal> Sistolica { get; set; }
        public Nullable<decimal> Diastolica { get; set; }
        public bool HTA_nueva { get; set; }
        public Nullable<int> Grado { get; set; }
        public bool Excesiva_somnolencia { get; set; }
        public bool Antecendente_de_SAS { get; set; }
        public bool Historia_de_higiene { get; set; }
        public bool Cumple_con_dos_o_mas { get; set; }
        public bool Evaluacion_via_aerea { get; set; }
        public bool Apto_para_conducir_vehiculos { get; set; }
        public byte[] Firma { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public bool Modificado { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
        public string Estado { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
