//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosExtra
    {
        public int Id_ArchivoExtra { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public string Descripcion { get; set; }
        public string link { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
