//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSO
    {
        public int Id_CSO { get; set; }
        public string Antiguedad_en_el_puesto { get; set; }
        public string Tiempo_en_la_empresa { get; set; }
        public string Área_de_Trabajo { get; set; }
        public Nullable<System.DateTime> Anamnesis_ocupacional_ex_fisico { get; set; }
        public bool Hemograma_completo { get; set; }
        public bool Audiometria_tonal { get; set; }
        public bool Gicemia { get; set; }
        public bool Espirometria { get; set; }
        public bool Urea_creatinina { get; set; }
        public bool Panel_de_drogas_minimo_coc_thc_mtd_met { get; set; }
        public bool Tuberculosis { get; set; }
        public bool capacidad_fisica_test_manero { get; set; }
        public bool Examen_de_orina { get; set; }
        public bool Agudez_visual_agudeza_campo_profundidad_cromatismo { get; set; }
        public bool Perfil_Lipidico { get; set; }
        public bool Electrocardiograma_en_reposo { get; set; }
        public bool TGO_TGP { get; set; }
        public bool Radiografia_De_Torax_PA_Radiografia_lumbo_sacra { get; set; }
        public bool HBSAG_Hepatitis_C { get; set; }
        public string Otros { get; set; }
        public bool Apto { get; set; }
        public bool Apto_con_restriccion { get; set; }
        public bool No_Apto { get; set; }
        public bool Aplazado { get; set; }
        public string Recomendaciones_observaciones { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public byte[] Firma { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
