//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deteccion_SAS
    {
        public int Id_deteccion_SAS { get; set; }
        public string Tipo_Licensia { get; set; }
        public Nullable<bool> Trabaja_de_noche { get; set; }
        public Nullable<int> Dias_trabajo { get; set; }
        public Nullable<int> Dias_descanso { get; set; }
        public Nullable<int> Anos_trabajando_en_horario { get; set; }
        public Nullable<bool> Apnea_del_sueno { get; set; }
        public Nullable<System.DateTime> Ultimo_control { get; set; }
        public Nullable<bool> HTA { get; set; }
        public Nullable<decimal> Medicacion { get; set; }
        public Nullable<bool> Polisomnografia { get; set; }
        public Nullable<System.DateTime> Ultima_fecha_PSG { get; set; }
        public Nullable<bool> En_Mina { get; set; }
        public Nullable<bool> Fuera_de_mina { get; set; }
        public Nullable<bool> Se_cabeceo { get; set; }
        public Nullable<bool> Accidente_en_ultimas_5_horas_turno_nocturno_entre_14_17_pm { get; set; }
        public Nullable<bool> Ausencia_de_evidencia_maniobra_para_evitar_colicion { get; set; }
        public Nullable<bool> Colicion_frontal_cayo_precipicio_rio_poste_puente_estructura_sin_motivo { get; set; }
        public Nullable<bool> Invadio_otro_carril_se_desvio_sin_causa_aparente { get; set; }
        public Nullable<bool> Condutor_no_recuerda_10_segudos_antes_impacto { get; set; }
        public Nullable<bool> Conductor_tomo_medicacion_termino_tratamiendo_que_causa_somnolencia { get; set; }
        public Nullable<bool> Conductor_se_encontraba_en_hora_extra { get; set; }
        public Nullable<bool> Confirmado_somnolencia { get; set; }
        public Nullable<bool> Alta_sospecha_somnolencia { get; set; }
        public Nullable<bool> Escasa_evidencia_somnolencia { get; set; }
        public Nullable<bool> No_se_dispone_de_datos_suficientes { get; set; }
        public Nullable<bool> Accidente_no_debido_a_somnolencia { get; set; }
        public Nullable<bool> En_ultimos_5_anos_su_pareja_comenta_que_ronca { get; set; }
        public Nullable<bool> En_ultimos_5_anos_su_pareja_comenta_que_hace_ruidos_al_dormir { get; set; }
        public Nullable<bool> En_ultimos_5_anos_su_pareja_comenta_que_deja_de_respirar_al_dormir { get; set; }
        public Nullable<bool> Siente_que_tiene_mas_sueno_o_cansancio_que_companeros_de_trabajo { get; set; }
        public Nullable<bool> Tiene_algun_familiar_con_apnea_del_sueno { get; set; }
        public Nullable<bool> Algun_accidente_considerado_falla_humana { get; set; }
        public Nullable<bool> Recibe_tratamiento_para_Apnea_con_CPAP { get; set; }
        public Nullable<bool> Se_le_ha_realizado_una_PSG_durante_el_sueno { get; set; }
        public Nullable<decimal> Puntuacion_Epworth { get; set; }
        public Nullable<decimal> Total_puntos { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Talla { get; set; }
        public Nullable<decimal> IMC { get; set; }
        public Nullable<decimal> Circunferencia_cuello { get; set; }
        public Nullable<bool> Varon_normal { get; set; }
        public Nullable<bool> Mujer_normal { get; set; }
        public Nullable<decimal> P_Sistolica { get; set; }
        public Nullable<decimal> P_Diastolica { get; set; }
        public Nullable<bool> HTA_nueva { get; set; }
        public string MALLAMPATI { get; set; }
        public Nullable<bool> Riesgo_alto { get; set; }
        public Nullable<bool> Riesgo_medio { get; set; }
        public Nullable<bool> Riesgo_bajo { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public byte[] Firma { get; set; }
        public byte[] Firma_candidato { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
