//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpWorth
    {
        public int Id_EpWorth { get; set; }
        public Nullable<int> sentado_y_leyendo { get; set; }
        public Nullable<int> viendo_la_television { get; set; }
        public Nullable<int> sentado_inactivo_lugar_publico { get; set; }
        public Nullable<int> sentado_una_hora_pasajero { get; set; }
        public Nullable<int> tumbado_de_tarde_para_descansar { get; set; }
        public Nullable<int> sentado_hablando_con_otro { get; set; }
        public Nullable<int> sentado_tranquilo_despues_de_comida { get; set; }
        public Nullable<int> sentado_en_coche_por_unos_minutos_por_atasco { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public byte[] Firma { get; set; }
        public string firma_candidato { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
