//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen_Visual
    {
        public int Id_Examen_Visual { get; set; }
        public Nullable<int> Sin_corr_OD { get; set; }
        public Nullable<int> Sin_corr_OS { get; set; }
        public Nullable<int> Sin_corr_AO { get; set; }
        public Nullable<int> Con_corr_OD { get; set; }
        public Nullable<int> Con_corr_OS { get; set; }
        public Nullable<int> Con_corr_AO { get; set; }
        public string AVC_Ambos_ojos { get; set; }
        public string Panorama_Normal_1 { get; set; }
        public string Panorama_Normal_2 { get; set; }
        public string Panorama_Normal_3 { get; set; }
        public string Panorama_Normal_4 { get; set; }
        public string Panorama_Normal_5 { get; set; }
        public string Panorama_Normal_6 { get; set; }
        public string Panorama_Normal_7 { get; set; }
        public string Panorama_Normal_8 { get; set; }
        public string Panorama_Normal_9 { get; set; }
        public string Panorama_Normal_10 { get; set; }
        public string Panorama_Normal_11 { get; set; }
        public string Deficiencias_Rojo_y_Verde_1 { get; set; }
        public string Deficiencias_Rojo_y_Verde_2 { get; set; }
        public string Deficiencias_Rojo_y_Verde_3 { get; set; }
        public string Deficiencias_Rojo_y_Verde_4 { get; set; }
        public string Deficiencias_Rojo_y_Verde_5 { get; set; }
        public string Deficiencias_Rojo_y_Verde_6 { get; set; }
        public string Deficiencias_Rojo_y_Verde_7 { get; set; }
        public string Deficiencias_Rojo_y_Verde_8 { get; set; }
        public string Deficiencias_Rojo_y_Verde_9 { get; set; }
        public string Deficiencias_Rojo_y_Verde_10 { get; set; }
        public string Deficiencias_Rojo_y_Verde_11 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_1 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_2 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_3 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_4 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_5 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_6 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_7 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_8 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_9 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_10 { get; set; }
        public string Ceguera_total_o_deilidad_cromatica_11 { get; set; }
        public string Respuesta_del_sujeto1 { get; set; }
        public string Respuesta_del_sujeto2 { get; set; }
        public string Respuesta_del_sujeto3 { get; set; }
        public string Respuesta_del_sujeto4 { get; set; }
        public string Respuesta_del_sujeto5 { get; set; }
        public string Respuesta_del_sujeto6 { get; set; }
        public string Respuesta_del_sujeto7 { get; set; }
        public string Respuesta_del_sujeto8 { get; set; }
        public string Respuesta_del_sujeto9 { get; set; }
        public string Respuesta_del_sujeto10 { get; set; }
        public string Respuesta_del_sujeto11 { get; set; }
        public string Ojo_derecho_TS { get; set; }
        public string Ojo_derecho_NS { get; set; }
        public string Ojo_derecho_TI { get; set; }
        public string Ojo_derecho_NI { get; set; }
        public string Ojo_izquierdo_TS { get; set; }
        public string Ojo_izquierdo_NS { get; set; }
        public string Ojo_izquierdo_TI { get; set; }
        public string Ojo_izquierdo_NI { get; set; }
        public Nullable<int> Persona_normal_12 { get; set; }
        public Nullable<int> Deficiencia_rojo_y_verde_LEVE_12 { get; set; }
        public Nullable<int> Protanopia_y_protanomalia_12 { get; set; }
        public Nullable<int> Deuteranopia_y_deuteronomalia_12 { get; set; }
        public Nullable<int> Respuesta_del_sujeto_12 { get; set; }
        public Nullable<int> Persona_normal_13 { get; set; }
        public Nullable<int> Deficiencia_rojo_y_verde_LEVE_13 { get; set; }
        public Nullable<int> Protanopia_y_protanomalia_13 { get; set; }
        public Nullable<int> Deuteranopia_y_deuteronomalia_13 { get; set; }
        public Nullable<int> Respuesta_del_sujeto_13 { get; set; }
        public string Respuesta_del_sujeto_14 { get; set; }
        public string Comentarios_ { get; set; }
        public string Agudeza_Visual_ { get; set; }
        public string Vision_cromatica { get; set; }
        public string Campos_Visuales_OD { get; set; }
        public string Campos_visuales_OS { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public byte[] Firma { get; set; }
        public string Resultado { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
