//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_general
    {
        public int Id_Info_General { get; set; }
        public string Empresa { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Departamento { get; set; }
        public string Posicion { get; set; }
        public string Tipo_de_evaluacion { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public string Cedula { get; set; }
        public Nullable<System.DateTime> Fecha_de_nacimiento { get; set; }
        public string Edad { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
        public Nullable<bool> Pre_espirometria { get; set; }
        public Nullable<bool> Espirometria { get; set; }
        public Nullable<bool> Audiometria { get; set; }
        public Nullable<bool> Capacidad_fisica { get; set; }
        public Nullable<bool> Laboratorio { get; set; }
        public Nullable<bool> Radiografia { get; set; }
        public Nullable<bool> Hemografia { get; set; }
        public Nullable<bool> EKG { get; set; }
        public Nullable<bool> Examen_visual { get; set; }
        public Nullable<bool> Bateria_de_un_mes { get; set; }
        public Nullable<bool> Bateria_Completa { get; set; }
        public Nullable<bool> Historia_clinica_y_examen_fisico { get; set; }
        public bool Consentimiento_informado { get; set; }
        public string Estado { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
