//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratorio
    {
        public int Id_Laboratorio { get; set; }
        public string Color { get; set; }
        public string Olor { get; set; }
        public string Aspecto { get; set; }
        public Nullable<decimal> PH { get; set; }
        public Nullable<int> Densidad { get; set; }
        public string Nitritos { get; set; }
        public string Glucosa { get; set; }
        public string Albumina { get; set; }
        public string Acetona { get; set; }
        public string Bilirrubina { get; set; }
        public string Urobilinógeno { get; set; }
        public string Pigmentos_biliares { get; set; }
        public string Hemoglobina { get; set; }
        public string Sangre_oculta { get; set; }
        public string Examen_Microscópico { get; set; }
        public string Células_renales { get; set; }
        public string Leucocitos { get; set; }
        public string Hematíes { get; set; }
        public string Células_epiteliales { get; set; }
        public string Bacterias { get; set; }
        public string Fibras_mucosas { get; set; }
        public string Levaduras { get; set; }
        public string Cristales { get; set; }
        public string Cilindros { get; set; }
        public string Parásitos { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public byte[] firma { get; set; }
        public string Glicemia_alarma { get; set; }
        public Nullable<int> Glicemia_Resultado { get; set; }
        public string Colesterol_total_alarma { get; set; }
        public Nullable<int> Colesterol_total_resultado { get; set; }
        public string C_HDL_alarma { get; set; }
        public Nullable<int> C_HDL_resultado { get; set; }
        public string SGPT_ALT_alarma { get; set; }
        public Nullable<int> SGPT_ALT_resultado { get; set; }
        public string SGOT_ALT_alarma { get; set; }
        public Nullable<int> SGOT_ALT_resultado { get; set; }
        public string C_LDL_alarma { get; set; }
        public Nullable<int> C_LDL_resultado { get; set; }
        public string Creatinina_alarma { get; set; }
        public Nullable<decimal> Creatinina_resultado { get; set; }
        public string VDRL { get; set; }
        public string Bacilo_de_Koch { get; set; }
        public string HBsAg { get; set; }
        public string HCV { get; set; }
        public string Eritrosedimentacion { get; set; }
        public string Cocaina { get; set; }
        public string Anfetaminas { get; set; }
        public string Opiaceos { get; set; }
        public string Marihuana { get; set; }
        public string Determinacion1 { get; set; }
        public string Alarma1 { get; set; }
        public Nullable<int> Resultado1 { get; set; }
        public string Unidad1 { get; set; }
        public Nullable<int> Valor_de_Referencia_11 { get; set; }
        public Nullable<int> Valor_de_Referencia_12 { get; set; }
        public string Metodo1 { get; set; }
        public string Determinacion2 { get; set; }
        public string Alarma2 { get; set; }
        public Nullable<int> Resultado2 { get; set; }
        public string Unidad2 { get; set; }
        public Nullable<int> Valor_de_Referencia_21 { get; set; }
        public Nullable<int> Valor_de_Referencia_22 { get; set; }
        public string Metodo2 { get; set; }
        public string Determinacion3 { get; set; }
        public string Alarma3 { get; set; }
        public Nullable<int> Resultado3 { get; set; }
        public string Unidad3 { get; set; }
        public Nullable<int> Valor_de_Referencia_31 { get; set; }
        public Nullable<int> Valor_de_Referencia_32 { get; set; }
        public string Metodo3 { get; set; }
        public string Determinacion4 { get; set; }
        public string Alarma4 { get; set; }
        public Nullable<int> Resultado4 { get; set; }
        public string Unidad4 { get; set; }
        public Nullable<int> Valor_de_Referencia_41 { get; set; }
        public Nullable<int> Valor_de_Referencia_42 { get; set; }
        public string Metodo4 { get; set; }
        public string Determinacion5 { get; set; }
        public string Alarma5 { get; set; }
        public Nullable<int> Resultado5 { get; set; }
        public string Unidad5 { get; set; }
        public Nullable<int> Valor_de_Referencia_51 { get; set; }
        public Nullable<int> Valor_de_Referencia_52 { get; set; }
        public string Metodo5 { get; set; }
        public string Determinacion6 { get; set; }
        public string Alarma6 { get; set; }
        public Nullable<int> Resultado6 { get; set; }
        public string Unidad6 { get; set; }
        public Nullable<int> Valor_de_Referencia_61 { get; set; }
        public Nullable<int> Valor_de_Referencia_62 { get; set; }
        public string Metodo6 { get; set; }
        public string Determinacion7 { get; set; }
        public string Alarma7 { get; set; }
        public Nullable<int> Resultado7 { get; set; }
        public string Unidad7 { get; set; }
        public Nullable<int> Valor_de_Referencia_71 { get; set; }
        public Nullable<int> Valor_de_Referencia_72 { get; set; }
        public string Metodo7 { get; set; }
        public string Determinacion8 { get; set; }
        public string Alarma8 { get; set; }
        public Nullable<decimal> Resultado8 { get; set; }
        public string Unidad8 { get; set; }
        public Nullable<decimal> Valor_de_Referencia_81 { get; set; }
        public Nullable<decimal> Valor_de_Referencia_82 { get; set; }
        public string Metodo8 { get; set; }
        public string Determinacion9 { get; set; }
        public string Alarma9 { get; set; }
        public Nullable<int> Resultado9 { get; set; }
        public string Unidad9 { get; set; }
        public Nullable<int> Valor_de_Referencia_91 { get; set; }
        public Nullable<int> Valor_de_Referencia_92 { get; set; }
        public string Metodo9 { get; set; }
        public string Determinacion10 { get; set; }
        public string Alarma10 { get; set; }
        public Nullable<int> Resultado10 { get; set; }
        public string Unidad10 { get; set; }
        public Nullable<int> Valor_de_Referencia_101 { get; set; }
        public Nullable<int> Valor_de_Referencia_102 { get; set; }
        public string Metodo10 { get; set; }
        public string Determinacion11 { get; set; }
        public string Alarma11 { get; set; }
        public Nullable<int> Resultado11 { get; set; }
        public string Unidad11 { get; set; }
        public Nullable<int> Valor_de_Referencia_111 { get; set; }
        public Nullable<int> Valor_de_Referencia_112 { get; set; }
        public string Metodo11 { get; set; }
        public string Determinacion12 { get; set; }
        public string Alarma12 { get; set; }
        public Nullable<int> Resultado12 { get; set; }
        public string Unidad12 { get; set; }
        public Nullable<int> Valor_de_Referencia_121 { get; set; }
        public Nullable<int> Valor_de_Referencia_122 { get; set; }
        public string Metodo12 { get; set; }
        public string Serologia_condicion_1 { get; set; }
        public string Serologia_resultado_1 { get; set; }
        public string Serologia_metodo_1 { get; set; }
        public string Serologia_condicion_2 { get; set; }
        public string Serologia_resultado_2 { get; set; }
        public string Serologia_metodo_2 { get; set; }
        public string Serologia_condicion_3 { get; set; }
        public string Serologia_resultado_3 { get; set; }
        public string Serologia_metodo_3 { get; set; }
        public string Serologia_condicion_4 { get; set; }
        public string Serologia_resultado_4 { get; set; }
        public string Serologia_metodo_4 { get; set; }
        public byte[] Firma1 { get; set; }
        public string Trigliceridos_alarma { get; set; }
        public Nullable<int> Trigliceridos_reultado { get; set; }
        public string Notas { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
        public string Estado { get; set; }
    
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
