//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mareo
    {
        public int Id_Mareo { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Pulso { get; set; }
        public Nullable<int> Frecuencia_Cardiaca_Maxima { get; set; }
        public Nullable<decimal> Tension_Arterial1 { get; set; }
        public Nullable<decimal> Tension_Arterial2 { get; set; }
        public Nullable<decimal> C65__Frecuencia_Cartdiaca_Maxima { get; set; }
        public Nullable<decimal> Primera_Carga { get; set; }
        public Nullable<decimal> Segund_Carga { get; set; }
        public Nullable<decimal> Tercera_Carga { get; set; }
        public Nullable<decimal> Cuarta_Carga { get; set; }
        public Nullable<decimal> Quinta_Carga { get; set; }
        public string VO2Max { get; set; }
        public string Factor_Correccion { get; set; }
        public Nullable<decimal> Resultado { get; set; }
        public Nullable<decimal> Resultado2 { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Id_Formulario_S_O { get; set; }
        public byte[] Firma { get; set; }
        public Nullable<bool> Modificado { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public Nullable<int> Usuario_que_modifico { get; set; }
  
        public virtual Formulario_S_O Formulario_S_O { get; set; }
    }
}
