//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int Mesage_id { get; set; }
        public string Mensaje1 { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Id_usuario { get; set; }
        public Nullable<int> Id_usuario_recive { get; set; }
        public Nullable<System.DateTime> FechaYhora { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
