//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ceisamco_form_s_oEntities_1 : DbContext
    {
        public ceisamco_form_s_oEntities_1()
            : base("name=ceisamco_form_s_oEntities_11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consentimiento_Informado> Consentimiento_Informado { get; set; }
        public virtual DbSet<CSO> CSO { get; set; }
        public virtual DbSet<EKG> EKG { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Formulario_S_O> Formulario_S_O { get; set; }
        public virtual DbSet<Hemograma> Hemograma { get; set; }
        public virtual DbSet<Info_general> Info_general { get; set; }
        public virtual DbSet<Pre_espirometria> Pre_espirometria { get; set; }
        public virtual DbSet<RayosX> RayosX { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Rol> Usuario_Rol { get; set; }
        public virtual DbSet<Usuario_Empresa> Usuario_Empresa { get; set; }
        public virtual DbSet<Laboratorio> Laboratorio { get; set; }
        public virtual DbSet<Historia_Clinica> Historia_Clinica { get; set; }
        public virtual DbSet<Mareo> Mareo { get; set; }
        public virtual DbSet<Audiometria> Audiometria { get; set; }
        public virtual DbSet<Examen_Visual> Examen_Visual { get; set; }
        public virtual DbSet<Espirometria> Espirometria { get; set; }
    }
}
