//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebParaMelvin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ceisamco_form_s_oEntities : DbContext
    {
        public ceisamco_form_s_oEntities()
            : base("name=ceisamco_form_s_oEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audiometria> Audiometrias { get; set; }
        public virtual DbSet<Consentimiento_Informado> Consentimiento_Informado { get; set; }
        public virtual DbSet<CSO> CSOes { get; set; }
        public virtual DbSet<EKG> EKGs { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Espirometria> Espirometrias { get; set; }
        public virtual DbSet<Examen_Visual> Examen_Visual { get; set; }
        public virtual DbSet<Formulario_S_O> Formulario_S_O { get; set; }
        public virtual DbSet<Hemograma> Hemogramas { get; set; }
        public virtual DbSet<Historia_Clinica> Historia_Clinica { get; set; }
        public virtual DbSet<Info_general> Info_general { get; set; }
        public virtual DbSet<Laboratorio> Laboratorios { get; set; }
        public virtual DbSet<Mareo> Mareos { get; set; }
        public virtual DbSet<Pre_espirometria> Pre_espirometria { get; set; }
        public virtual DbSet<RayosX> RayosXes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Usuario_Rol> Usuario_Rol { get; set; }
        public virtual DbSet<Usuario_Empresa> Usuario_Empresa { get; set; }
    }
}
